import React, { useState } from 'react'
import Input from './Input'
import Button from './Button'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faChevronDown } from '@fortawesome/free-solid-svg-icons'

export default function Seo() {
    const [showseo, setShowSeo] = useState(false)
  return (
    <div style={{boxShadow:" rgba(0,0,0,.05) 0 1px 4px"}}  className=" w-full space-y-3 px-3 py-4 bg-white  rounded-lg">
    <div onClick={() =>setShowSeo(!showseo)} className=" flex justify-between">
    <div className=" py-2 w-[80%] border-b border-dashed">
    <h1 className=" ">SEO Settings</h1>
    <p className=" text-xs font-light text-slate-600 text-[11px]">Add search engine title and description to make this product easier to find</p>
    </div>
    <FontAwesomeIcon icon={faChevronDown} className=' py-4 text-slate-600 ' />
    </div>
       <div className={` ${showseo ? " block " : " hidden "} space-y-2`}>
       <div className=" space-y-2">
        <Input  placeholder="Seo Title" label="Title"  />
        <p className=" text-[11px] font-light text-slate-600">( If empty, the preview shows what will be autogenerated. )</p>
        </div>
        <div className=" space-y-2">
        <div className=" space-y-2">
        <label htmlFor="" className='ml-1 space-x-0.5 font-light text-sm text-slate-500'><span className="">Description</span></label>
        <textarea name="" id="" className='w-full py-2.5 border focus:ring-blue-600 focus:outline-blue-500 px-4 placeholder:text-slate-300 rounded-lg' rows="5"></textarea>
        </div>
       <Button bgColor="bg-[#a855f7]" label="save" />
        </div>
       </div>
       </div>
  )
}
